# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa715c53635ac5a2b7a09eea42f8a16d427cb1c2cd73dee5e3182ba0e30525c3a5397975eaef273ecce554bf1958a8092893ac859e0707ffa06f1ec1f3419566

test:
  secret_key_base: c4dc3df887e3f61325327ffb0b62fbfefa5686746878e84666218c2d0cdd5f3ded2fd355fd3d8f8cc3356c6a8024a65a495667d0062622b1aca15568d53d7867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
